#!/bin/python3
import sys
import os
import uuid
import subprocess
import logging
import argparse
import json

boot_device = subprocess.check_output(["df", "-P", "/boot"]).decode("utf-8").strip().split("\n",1)[1]
print(boot_device)

sys.exit(0)
