#! /usr/bin/bash
BOOT_BLOCK=/dev/$(lsblk -ndo pkname $(df -P "/boot" | awk 'END{print $1}'))
BOOT_DEVICE=$(df -P -h -T "/boot" | awk 'END{print $1}')
BOOT_DEVICE_NUM=$(echo $BOOT_DEVICE | sed "s#$BOOT_BLOCK##")
ROOT_UUID=$(findmnt --fstab -T / -o SOURCE | tail +2)
ROOT_FLAGS=$(findmnt --fstab -T / -o Options | tail +2)
if [ -d /sys/firmware/efi ]
then
	echo "UEFI Detected! Installing systemd-boot"
	sudo parted $BOOT_BLOCK set $BOOT_DEVICE_NUM bls_boot on
	for i in $(/usr/bin/apt --installed list 2>/dev/null | grep grub | cut -d"/" -f1 | grep -vi grub-common) ; do apt remove -y $i || echo "no action needed for $i" ; done || true
	bootctl install || true
	SDB_EFI=$(bootctl -p) || true
	cp -f /etc/vanilla/config/loader.conf $SDB_EFI/loader/loader.conf || true
	mkdir -p /tmp/update-systemd-boot || true
	echo "root=$ROOT_UUID rootflags=$ROOT_FLAGS quiet splash bgrt_disable $vt_handoff" > /tmp/update-systemd-boot/options || true
	sudo update-systemd-boot -o || true
	sudo update-systemd-boot -x || true
fi
